name: Deploy Theme to DonWeb FTP

on:
  push:
    branches:
      - main
    paths:
      - 'vendaval-theme/**'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Install LFTP and Deploy
      run: |
        sudo apt-get update
        sudo apt-get install lftp -y
        lftp -c "
        set ftp:ssl-allow true
        set ftp:ssl-force true
        set ssl:verify-certificate no
        set ftp:passive-mode true
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
        mirror -R --verbose ./vendaval-theme/ /wp-content/themes/vendaval-theme/
        "
